export const pokemonDocumentId = "3VrSEef3dfMKatd1eM0m"
export type GalleryViewType = "tile" | "card"
export type StudioViewType = "create" | "update" | "db"
export type AppType = "Studio" | "Gallery" | "Home" | "Dashboard"
export type DBType = "set" | "cardType" | "type" | "condition" | "pokemon"
